-- Run in Neon SQL Editor (https://console.neon.tech), na 002_gesprek_lineage.sql
-- Verbeterplanning Tijdlijn: gedeeld, live-bewerkbaar bord (vervangt de
-- localStorage-only standalone tool Precon_Tijdlijn.html).
--
-- `code` is de stabiele projectsleutel (bv. "KMO01") — overeenkomstig het
-- `id`-veld uit de bron-tool, niet het cosmetische `code`-weergavelabel
-- (dat voor "PK04" een decoratief " ❄"-achtervoegsel bevatte).
--
-- Lege status ('') wordt gerepresenteerd door een AFWEZIGE rij in de
-- status-tabellen, net als het ontbreken van een localStorage-key in de bron.

CREATE TABLE IF NOT EXISTS verbeterplanning_projects (
  code        TEXT PRIMARY KEY,
  title       TEXT NOT NULL,
  mtlid       TEXT NOT NULL DEFAULT '',
  trekker     TEXT NOT NULL DEFAULT '',
  team        TEXT NOT NULL DEFAULT '',
  rg          TEXT NOT NULL DEFAULT '',
  kpi         TEXT NOT NULL DEFAULT '',
  "group"     TEXT NOT NULL
              CHECK ("group" IN (
                'Klant- & Marktontwikkeling',
                'Préconners in hun kracht',
                'Digitale tools voor de professional',
                'Impact improvement'
              )),
  sort_order  INTEGER NOT NULL DEFAULT 0,
  created_by  TEXT NOT NULL,
  updated_by  TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vp_projects_group_sort
  ON verbeterplanning_projects ("group", sort_order);

CREATE TABLE IF NOT EXISTS verbeterplanning_project_status (
  project_code  TEXT NOT NULL REFERENCES verbeterplanning_projects(code) ON DELETE CASCADE,
  month_index   SMALLINT NOT NULL CHECK (month_index BETWEEN 0 AND 32),
  status        TEXT NOT NULL CHECK (status IN ('green', 'amber', 'red', 'purple')),
  updated_by    TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (project_code, month_index)
);

CREATE TABLE IF NOT EXISTS verbeterplanning_milestones (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_code  TEXT NOT NULL REFERENCES verbeterplanning_projects(code) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  sort_order    INTEGER NOT NULL DEFAULT 0,
  created_by    TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vp_milestones_project
  ON verbeterplanning_milestones (project_code, sort_order);

CREATE TABLE IF NOT EXISTS verbeterplanning_milestone_status (
  milestone_id  UUID NOT NULL REFERENCES verbeterplanning_milestones(id) ON DELETE CASCADE,
  month_index   SMALLINT NOT NULL CHECK (month_index BETWEEN 0 AND 32),
  status        TEXT NOT NULL CHECK (status IN ('green', 'amber', 'red', 'purple')),
  updated_by    TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (milestone_id, month_index)
);

CREATE TABLE IF NOT EXISTS verbeterplanning_kpis (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_code  TEXT NOT NULL REFERENCES verbeterplanning_projects(code) ON DELETE CASCADE,
  type          TEXT NOT NULL CHECK (type IN ('activiteit', 'resultaat')),
  description   TEXT NOT NULL DEFAULT '',
  sort_order    INTEGER NOT NULL DEFAULT 0,
  created_by    TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vp_kpis_project
  ON verbeterplanning_kpis (project_code, sort_order);

-- 4-staten cyclus (geen purple) — bewuste inconsistentie t.o.v. maand-status,
-- overgenomen uit de bron-tool (cycleKpiStatus gebruikte ['', 'green','amber','red']).
CREATE TABLE IF NOT EXISTS verbeterplanning_kpi_quarter_status (
  kpi_id        UUID NOT NULL REFERENCES verbeterplanning_kpis(id) ON DELETE CASCADE,
  quarter_index SMALLINT NOT NULL CHECK (quarter_index BETWEEN 0 AND 7),
  status        TEXT NOT NULL CHECK (status IN ('green', 'amber', 'red')),
  updated_by    TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kpi_id, quarter_index)
);

CREATE TABLE IF NOT EXISTS verbeterplanning_kpi_quarter_notes (
  kpi_id        UUID NOT NULL REFERENCES verbeterplanning_kpis(id) ON DELETE CASCADE,
  quarter_index SMALLINT NOT NULL CHECK (quarter_index BETWEEN 0 AND 7),
  note          TEXT NOT NULL DEFAULT '',
  updated_by    TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (kpi_id, quarter_index)
);

CREATE TABLE IF NOT EXISTS verbeterplanning_updates (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_code  TEXT NOT NULL REFERENCES verbeterplanning_projects(code) ON DELETE CASCADE,
  text          TEXT NOT NULL,
  created_by    TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vp_updates_project_created
  ON verbeterplanning_updates (project_code, created_at DESC);

-- Vaste kalender (18 entries, index 0-17: juni 2026 t/m november 2027).
-- Ontbrekende rij == alle velden leeg; niet elke maand hoeft een rij te hebben.
CREATE TABLE IF NOT EXISTS verbeterplanning_agenda (
  month_index   SMALLINT PRIMARY KEY CHECK (month_index BETWEEN 0 AND 17),
  datum         TEXT NOT NULL DEFAULT '',
  projecten     TEXT NOT NULL DEFAULT '',
  opmerkingen   TEXT NOT NULL DEFAULT '',
  updated_by    TEXT NOT NULL,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────
-- Seed data — letterlijke transcriptie van de huidige ingevulde data uit
-- Precon_Tijdlijn.html (PROJECTS-array + SEED_PROJECTS/SEED_CUSTOM_PROJECTS,
-- gegenereerd door een eenmalig hulpscript dat het HTML-bestand uitleest —
-- dit zijn de letterlijke resulterende INSERT-statements, geen placeholder-
-- data en geen script dat bij deploy draait). SEED_AGENDA bevat geen data
-- (alle 18 entries waren leeg), dus geen agenda-seed nodig.
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO verbeterplanning_projects (code, title, mtlid, trekker, team, rg, kpi, "group", sort_order, created_by, updated_by) VALUES
  ('KMO01', 'Groeiplan bestaande klanten', 'Marcel T', 'Silvion', 'Corry, Silvion, Jack, Nida', 'Randvoorwaardelijk', 'Nog niet SMART. Aantal klantevaluaties, gemiddelde omzet per klant, accountmanagement bezoeken, meer A-klanten.', 'Klant- & Marktontwikkeling', 10, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO02', 'Groeiplan België', 'Ard', 'Bram', 'Bram, Pieter, Sofie', 'Klant- en Marktontwikkeling', 'Omzet BE markt (k€): 770 (2024) → 950 (2025) → 1.150 (2026) → 1.400 (2027) → 2.500 (2030). Aantal FTE: ~40 (2030).', 'Klant- & Marktontwikkeling', 20, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO03', 'Groeiplan non-food', 'Marcel dH', 'Brighid', 'Silvion, Robin, Nora', 'Klant- en Marktontwikkeling', 'Omzet non-food (k€): 1.000 (2024) → 1.100 (2025) → 1.400 (2026) → 1.800 (2027).', 'Klant- & Marktontwikkeling', 30, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO04', 'Klantaanvraag opvolgingsproces', 'Ard', 'Judith', 'Ellis, Anne-Marij', 'Klant- en Marktontwikkeling', 'Nog niet SMART. Randvoorwaardelijk voor realisatie van doelen Précon.', 'Klant- & Marktontwikkeling', 40, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO05', 'Groeiplan Frankrijk', 'Marcel T', 'Heleen', 'Fabrice, Martine, Roos', 'Klant- en Marktontwikkeling', 'Omzet FR markt (k€): 0 (2024) → 100 (2025) → 200 (2026) → 300 (2027) → 400 (2028) → 500 (2030).', 'Klant- & Marktontwikkeling', 50, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO06', 'Diensten storyboard', 'Marcel dH', 'Ellis', 'Emma, Caro', 'Ondersteunend', 'Elk kwartaal extra opdracht (gem. €17.000 → €68.000/jr). Meer werkplezier.', 'Klant- & Marktontwikkeling', 60, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO07', 'Proactief netwerken', 'Marcel T', 'Aukje', 'Judith, Ellis', 'Ondersteunend', 'Bredere participatie professionals in sales. Betere zichtbaarheid Précon.', 'Klant- & Marktontwikkeling', 70, 'seed@precon.nl', 'seed@precon.nl'),
  ('KMO08', 'Groeiplan internationaal', 'Marcel T', 'Marcel T', 'Elizabeth, Camiel, Bram', 'Klant- en Marktontwikkeling', 'Winst (k€): 50/jr (2028) → 400 (2030).', 'Klant- & Marktontwikkeling', 80, 'seed@precon.nl', 'seed@precon.nl'),
  ('PK01', 'Persoonlijke ontwikkelpaden', 'Chantal', 'Chantal', 'Lisa, Emma, Anne-Marij, Ivo', 'Randvoorwaardelijk', 'Voldoen aan visie-essentie (punt 3 & 4). Eigenaarschap omhoog bij consultants.', 'Préconners in hun kracht', 10, 'seed@precon.nl', 'seed@precon.nl'),
  ('PK02', 'Leiderschapsprogramma', 'Chantal', 'Chantal', 'Roos vK, Ivo', 'Randvoorwaardelijk', 'Eind 2025: nulmeting per leider, strategisch groeiplan, start individueel groeitraject.', 'Préconners in hun kracht', 20, 'seed@precon.nl', 'seed@precon.nl'),
  ('PK03', 'Optimaliseren werkwijzen', 'Ard', 'Ester', 'Ester, Roos R', 'Ondersteunend', 'Werkwijzen kritisch geëvalueerd en bijgesteld op visie-essentie en kernwaarden.', 'Préconners in hun kracht', 30, 'seed@precon.nl', 'seed@precon.nl'),
  ('PK04', 'Wervingsmachine', 'Ard', 'Judith', 'Lisa (koelkast)', 'Randvoorwaardelijk', 'Succesvol wervingsproces dat aansluit bij nieuwe werkwijzen.', 'Préconners in hun kracht', 40, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP01', 'Digitale tools voor klanten', 'Marcel dH', 'Marcel dH', 'Emily, Gina, Caro, Corry, Pien, Sander', 'Digitale tools voor de professional', 'Recurrent omzet (k€): 700 (2024) → 800 (2025) → 920 (2026) → 1.050 (2027).', 'Digitale tools voor de professional', 10, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP02a', 'AI bij RA', 'Marcel dH', 'Emma Luca', 'Emma Luca, Jack, Jelle', 'Digitale tools voor de professional', 'Omzet groeiend: €10.000/jr (2027) → €100.000/jr (vanaf 2029).', 'Digitale tools voor de professional', 20, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP02b', 'AI bij non-food', 'Marcel dH', 'Emma Luca', 'Emma Luca, Jack, Jelle', 'Digitale tools voor de professional', 'Omzet groeiend: €10.000/jr (2027) → €100.000/jr (vanaf 2029).', 'Digitale tools voor de professional', 30, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP02c', 'AI bij PPWR', 'Marcel dH', 'Emma Luca', 'Emma Luca, Jack, Jelle', 'Digitale tools voor de professional', 'Onderdeel van bredere AI-strategie. KPIs worden bepaald bij opstart project.', 'Digitale tools voor de professional', 40, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP03A', 'Interne digitale tools', 'Marcel dH', 'tbd', 'Alida, Alinda, Sander vZ', 'Digitale tools voor de professional', 'Betere communicatie en kennisdeling. Minder tijdverlies aan "wiel opnieuw uitvinden".', 'Digitale tools voor de professional', 50, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP03B', 'AI voor intern gebruik', 'Marcel dH', 'Jelle', 'Sander V, Jack, Emma Luca, Joost, Sonja, Kim', 'Digitale tools voor de professional', 'Tijdsbesparing op intern werk. Hogere kwaliteit en snelheid van outputs.', 'Digitale tools voor de professional', 60, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP04', 'Oriëntatie QA software', 'Ard', 'Bas', 'Petra, Sander V, Corry', 'Digitale tools voor de professional', 'Inzicht in beschikbare softwareoplossingen (internationale scope).', 'Digitale tools voor de professional', 70, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP07', 'NPD module Quasydoc', 'Ard', 'Bas', '', 'Digitale tools voor de professional', 'Nieuwe module operationeel bij Quasydoc.', 'Digitale tools voor de professional', 80, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP08', 'Food Safety Bow Tie', 'Marcel T', 'Sander V', 'Paul, Marcel dH', 'Digitale tools voor de professional', 'Tool operationeel en inzetbaar bij klanten.', 'Digitale tools voor de professional', 90, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP09', 'Food Law Guide 2.0', 'Marcel dH', 'Jasmijn', '', 'Digitale tools voor de professional', 'Vernieuwde guide beschikbaar voor klanten en intern gebruik.', 'Digitale tools voor de professional', 100, 'seed@precon.nl', 'seed@precon.nl'),
  ('IMP01', 'Groeiplan duurzaamheid', 'Marcel T', 'Pauline', 'Josette, Ester, Emma Luca', 'Impact improvement', 'Omzet duurzaamheid (k€): 50 (2024) → 125 (2025) → 250 (2026) → 500 (2027) → 750 (2028) → 1.000 (2029) → 1.200 (2030).', 'Impact improvement', 10, 'seed@precon.nl', 'seed@precon.nl'),
  ('IMP02', 'Groeiplan learning', 'Marcel T', 'Coen', '', 'Impact improvement', 'Omzet Learning (k€): 1.100 (2024) → 1.250 (2025) → 1.400 (2026) → 1.550 (2027) → 1.700 (2028) → 1.850 (2029) → 2.000 (2030).', 'Impact improvement', 20, 'seed@precon.nl', 'seed@precon.nl'),
  ('IMP03', 'Groeiplan change management', 'Chantal', 'Martine', 'Sander V', 'Impact improvement', 'Salesaanpak en werkwijze ontwikkeld voor klanten met verbetervraagstukken.', 'Impact improvement', 30, 'seed@precon.nl', 'seed@precon.nl'),
  ('IMP04', 'BCORP certificering', 'Marcel T', 'Ester', 'Marcel dH', 'Bcorp certificering', 'Behalen en behouden B Corp certificering.', 'Impact improvement', 40, 'seed@precon.nl', 'seed@precon.nl'),
  ('DTP02d', 'AI voor GINO', 'Marcel dH', 'Sander', 'Sander,', 'Digitale tools voor de professional', 'GINO software via AI, doel: vanaf 1 nov klanten overzetten in het systeem', 'Digitale tools voor de professional', 110, 'seed@precon.nl', 'seed@precon.nl');

INSERT INTO verbeterplanning_project_status (project_code, month_index, status, updated_by) VALUES
  ('KMO01', 5, 'green', 'seed@precon.nl'),
  ('KMO01', 6, 'green', 'seed@precon.nl'),
  ('KMO01', 7, 'green', 'seed@precon.nl'),
  ('KMO01', 8, 'green', 'seed@precon.nl'),
  ('KMO01', 9, 'green', 'seed@precon.nl'),
  ('KMO01', 10, 'amber', 'seed@precon.nl'),
  ('KMO01', 11, 'green', 'seed@precon.nl'),
  ('KMO01', 12, 'green', 'seed@precon.nl'),
  ('KMO01', 13, 'purple', 'seed@precon.nl'),
  ('KMO01', 14, 'purple', 'seed@precon.nl'),
  ('KMO02', 2, 'green', 'seed@precon.nl'),
  ('KMO02', 3, 'amber', 'seed@precon.nl'),
  ('KMO02', 4, 'green', 'seed@precon.nl'),
  ('KMO02', 5, 'green', 'seed@precon.nl'),
  ('KMO02', 6, 'amber', 'seed@precon.nl'),
  ('KMO02', 7, 'amber', 'seed@precon.nl'),
  ('KMO02', 8, 'amber', 'seed@precon.nl'),
  ('KMO02', 9, 'amber', 'seed@precon.nl'),
  ('KMO02', 10, 'amber', 'seed@precon.nl'),
  ('KMO02', 11, 'amber', 'seed@precon.nl'),
  ('KMO02', 12, 'amber', 'seed@precon.nl'),
  ('KMO02', 13, 'purple', 'seed@precon.nl'),
  ('KMO02', 14, 'purple', 'seed@precon.nl'),
  ('KMO02', 15, 'purple', 'seed@precon.nl'),
  ('KMO02', 16, 'purple', 'seed@precon.nl'),
  ('KMO02', 17, 'purple', 'seed@precon.nl'),
  ('KMO03', 1, 'green', 'seed@precon.nl'),
  ('KMO03', 2, 'green', 'seed@precon.nl'),
  ('KMO03', 3, 'amber', 'seed@precon.nl'),
  ('KMO03', 4, 'green', 'seed@precon.nl'),
  ('KMO03', 5, 'green', 'seed@precon.nl'),
  ('KMO03', 6, 'green', 'seed@precon.nl'),
  ('KMO03', 7, 'green', 'seed@precon.nl'),
  ('KMO03', 8, 'green', 'seed@precon.nl'),
  ('KMO03', 9, 'green', 'seed@precon.nl'),
  ('KMO03', 10, 'green', 'seed@precon.nl'),
  ('KMO03', 11, 'green', 'seed@precon.nl'),
  ('KMO03', 12, 'green', 'seed@precon.nl'),
  ('KMO03', 13, 'purple', 'seed@precon.nl'),
  ('KMO03', 14, 'purple', 'seed@precon.nl'),
  ('KMO04', 3, 'green', 'seed@precon.nl'),
  ('KMO04', 4, 'green', 'seed@precon.nl'),
  ('KMO04', 5, 'green', 'seed@precon.nl'),
  ('KMO04', 6, 'green', 'seed@precon.nl'),
  ('KMO04', 7, 'green', 'seed@precon.nl'),
  ('KMO04', 8, 'green', 'seed@precon.nl'),
  ('KMO04', 9, 'green', 'seed@precon.nl'),
  ('KMO04', 10, 'green', 'seed@precon.nl'),
  ('KMO04', 11, 'green', 'seed@precon.nl'),
  ('KMO04', 12, 'green', 'seed@precon.nl'),
  ('KMO04', 13, 'green', 'seed@precon.nl'),
  ('KMO05', 5, 'green', 'seed@precon.nl'),
  ('KMO05', 6, 'green', 'seed@precon.nl'),
  ('KMO05', 7, 'green', 'seed@precon.nl'),
  ('KMO05', 8, 'amber', 'seed@precon.nl'),
  ('KMO05', 9, 'amber', 'seed@precon.nl'),
  ('KMO05', 10, 'amber', 'seed@precon.nl'),
  ('KMO05', 11, 'amber', 'seed@precon.nl'),
  ('KMO05', 12, 'amber', 'seed@precon.nl'),
  ('KMO05', 13, 'amber', 'seed@precon.nl'),
  ('KMO05', 14, 'purple', 'seed@precon.nl'),
  ('KMO05', 15, 'purple', 'seed@precon.nl'),
  ('KMO05', 16, 'purple', 'seed@precon.nl'),
  ('KMO05', 17, 'purple', 'seed@precon.nl'),
  ('KMO05', 18, 'purple', 'seed@precon.nl'),
  ('KMO05', 19, 'purple', 'seed@precon.nl'),
  ('KMO05', 20, 'purple', 'seed@precon.nl'),
  ('KMO06', 20, 'purple', 'seed@precon.nl'),
  ('KMO06', 21, 'purple', 'seed@precon.nl'),
  ('KMO06', 22, 'purple', 'seed@precon.nl'),
  ('KMO06', 23, 'purple', 'seed@precon.nl'),
  ('KMO06', 24, 'purple', 'seed@precon.nl'),
  ('KMO06', 25, 'purple', 'seed@precon.nl'),
  ('KMO06', 26, 'purple', 'seed@precon.nl'),
  ('KMO06', 27, 'purple', 'seed@precon.nl'),
  ('KMO06', 28, 'purple', 'seed@precon.nl'),
  ('KMO06', 29, 'purple', 'seed@precon.nl'),
  ('KMO07', 11, 'green', 'seed@precon.nl'),
  ('KMO07', 12, 'green', 'seed@precon.nl'),
  ('KMO07', 13, 'green', 'seed@precon.nl'),
  ('KMO07', 14, 'green', 'seed@precon.nl'),
  ('KMO07', 15, 'purple', 'seed@precon.nl'),
  ('KMO07', 16, 'purple', 'seed@precon.nl'),
  ('KMO07', 17, 'purple', 'seed@precon.nl'),
  ('KMO07', 18, 'purple', 'seed@precon.nl'),
  ('KMO07', 19, 'purple', 'seed@precon.nl'),
  ('KMO07', 20, 'purple', 'seed@precon.nl'),
  ('KMO07', 21, 'purple', 'seed@precon.nl'),
  ('KMO07', 22, 'purple', 'seed@precon.nl'),
  ('KMO07', 23, 'purple', 'seed@precon.nl'),
  ('KMO07', 24, 'purple', 'seed@precon.nl'),
  ('KMO07', 25, 'purple', 'seed@precon.nl'),
  ('KMO07', 26, 'purple', 'seed@precon.nl'),
  ('KMO08', 16, 'purple', 'seed@precon.nl'),
  ('KMO08', 17, 'purple', 'seed@precon.nl'),
  ('KMO08', 18, 'purple', 'seed@precon.nl'),
  ('KMO08', 19, 'purple', 'seed@precon.nl'),
  ('KMO08', 20, 'purple', 'seed@precon.nl'),
  ('KMO08', 21, 'purple', 'seed@precon.nl'),
  ('KMO08', 22, 'purple', 'seed@precon.nl'),
  ('KMO08', 23, 'purple', 'seed@precon.nl'),
  ('KMO08', 24, 'purple', 'seed@precon.nl'),
  ('KMO08', 25, 'purple', 'seed@precon.nl'),
  ('PK01', 1, 'green', 'seed@precon.nl'),
  ('PK01', 2, 'green', 'seed@precon.nl'),
  ('PK01', 3, 'green', 'seed@precon.nl'),
  ('PK01', 4, 'green', 'seed@precon.nl'),
  ('PK01', 5, 'amber', 'seed@precon.nl'),
  ('PK01', 6, 'amber', 'seed@precon.nl'),
  ('PK01', 7, 'green', 'seed@precon.nl'),
  ('PK01', 8, 'green', 'seed@precon.nl'),
  ('PK01', 9, 'green', 'seed@precon.nl'),
  ('PK01', 10, 'green', 'seed@precon.nl'),
  ('PK01', 11, 'green', 'seed@precon.nl'),
  ('PK01', 12, 'green', 'seed@precon.nl'),
  ('PK01', 13, 'green', 'seed@precon.nl'),
  ('PK01', 14, 'green', 'seed@precon.nl'),
  ('PK01', 15, 'purple', 'seed@precon.nl'),
  ('PK01', 16, 'purple', 'seed@precon.nl'),
  ('PK01', 17, 'purple', 'seed@precon.nl'),
  ('PK01', 18, 'purple', 'seed@precon.nl'),
  ('PK01', 19, 'purple', 'seed@precon.nl'),
  ('PK01', 20, 'purple', 'seed@precon.nl'),
  ('PK01', 21, 'purple', 'seed@precon.nl'),
  ('PK01', 22, 'purple', 'seed@precon.nl'),
  ('PK01', 23, 'purple', 'seed@precon.nl'),
  ('PK01', 24, 'purple', 'seed@precon.nl'),
  ('PK01', 25, 'purple', 'seed@precon.nl'),
  ('PK01', 26, 'purple', 'seed@precon.nl'),
  ('PK01', 27, 'purple', 'seed@precon.nl'),
  ('PK01', 28, 'purple', 'seed@precon.nl'),
  ('PK01', 29, 'purple', 'seed@precon.nl'),
  ('PK01', 30, 'purple', 'seed@precon.nl'),
  ('PK02', 6, 'amber', 'seed@precon.nl'),
  ('PK02', 7, 'amber', 'seed@precon.nl'),
  ('PK02', 8, 'green', 'seed@precon.nl'),
  ('PK02', 9, 'green', 'seed@precon.nl'),
  ('PK02', 10, 'green', 'seed@precon.nl'),
  ('PK02', 11, 'green', 'seed@precon.nl'),
  ('PK02', 12, 'green', 'seed@precon.nl'),
  ('PK02', 13, 'green', 'seed@precon.nl'),
  ('PK02', 14, 'purple', 'seed@precon.nl'),
  ('PK02', 15, 'purple', 'seed@precon.nl'),
  ('PK02', 16, 'purple', 'seed@precon.nl'),
  ('PK02', 17, 'purple', 'seed@precon.nl'),
  ('PK02', 18, 'purple', 'seed@precon.nl'),
  ('PK02', 19, 'purple', 'seed@precon.nl'),
  ('PK03', 18, 'purple', 'seed@precon.nl'),
  ('PK03', 19, 'purple', 'seed@precon.nl'),
  ('PK03', 20, 'purple', 'seed@precon.nl'),
  ('PK03', 21, 'purple', 'seed@precon.nl'),
  ('PK03', 22, 'purple', 'seed@precon.nl'),
  ('PK03', 23, 'purple', 'seed@precon.nl'),
  ('PK03', 24, 'purple', 'seed@precon.nl'),
  ('PK03', 25, 'purple', 'seed@precon.nl'),
  ('PK03', 26, 'purple', 'seed@precon.nl'),
  ('DTP01', 2, 'green', 'seed@precon.nl'),
  ('DTP01', 3, 'amber', 'seed@precon.nl'),
  ('DTP01', 4, 'amber', 'seed@precon.nl'),
  ('DTP01', 5, 'amber', 'seed@precon.nl'),
  ('DTP01', 6, 'amber', 'seed@precon.nl'),
  ('DTP01', 7, 'amber', 'seed@precon.nl'),
  ('DTP01', 8, 'amber', 'seed@precon.nl'),
  ('DTP01', 9, 'red', 'seed@precon.nl'),
  ('DTP01', 10, 'red', 'seed@precon.nl'),
  ('DTP01', 11, 'amber', 'seed@precon.nl'),
  ('DTP01', 12, 'amber', 'seed@precon.nl'),
  ('DTP01', 13, 'amber', 'seed@precon.nl'),
  ('DTP02a', 5, 'green', 'seed@precon.nl'),
  ('DTP02a', 6, 'green', 'seed@precon.nl'),
  ('DTP02a', 7, 'green', 'seed@precon.nl'),
  ('DTP02a', 8, 'green', 'seed@precon.nl'),
  ('DTP02a', 9, 'green', 'seed@precon.nl'),
  ('DTP02a', 10, 'green', 'seed@precon.nl'),
  ('DTP02a', 11, 'green', 'seed@precon.nl'),
  ('DTP02a', 12, 'green', 'seed@precon.nl'),
  ('DTP02a', 13, 'green', 'seed@precon.nl'),
  ('DTP02b', 12, 'green', 'seed@precon.nl'),
  ('DTP02b', 13, 'green', 'seed@precon.nl'),
  ('DTP02b', 14, 'purple', 'seed@precon.nl'),
  ('DTP02b', 15, 'purple', 'seed@precon.nl'),
  ('DTP02b', 16, 'purple', 'seed@precon.nl'),
  ('DTP02b', 17, 'purple', 'seed@precon.nl'),
  ('DTP02b', 18, 'purple', 'seed@precon.nl'),
  ('DTP02b', 19, 'purple', 'seed@precon.nl'),
  ('DTP02b', 20, 'purple', 'seed@precon.nl'),
  ('DTP02b', 21, 'purple', 'seed@precon.nl'),
  ('DTP02b', 22, 'purple', 'seed@precon.nl'),
  ('DTP02c', 12, 'green', 'seed@precon.nl'),
  ('DTP02c', 13, 'green', 'seed@precon.nl'),
  ('DTP02c', 14, 'purple', 'seed@precon.nl'),
  ('DTP02c', 15, 'purple', 'seed@precon.nl'),
  ('DTP02c', 16, 'purple', 'seed@precon.nl'),
  ('DTP02c', 17, 'purple', 'seed@precon.nl'),
  ('DTP02c', 18, 'purple', 'seed@precon.nl'),
  ('DTP02c', 19, 'purple', 'seed@precon.nl'),
  ('DTP02c', 20, 'purple', 'seed@precon.nl'),
  ('DTP02c', 21, 'purple', 'seed@precon.nl'),
  ('DTP02c', 22, 'purple', 'seed@precon.nl'),
  ('DTP02d', 13, 'green', 'seed@precon.nl'),
  ('DTP02d', 14, 'purple', 'seed@precon.nl'),
  ('DTP02d', 15, 'purple', 'seed@precon.nl'),
  ('DTP02d', 16, 'purple', 'seed@precon.nl'),
  ('DTP02d', 17, 'purple', 'seed@precon.nl'),
  ('DTP02d', 18, 'purple', 'seed@precon.nl'),
  ('DTP02d', 19, 'purple', 'seed@precon.nl'),
  ('DTP02d', 20, 'purple', 'seed@precon.nl'),
  ('DTP03A', 17, 'purple', 'seed@precon.nl'),
  ('DTP03A', 18, 'purple', 'seed@precon.nl'),
  ('DTP03A', 19, 'purple', 'seed@precon.nl'),
  ('DTP03A', 20, 'purple', 'seed@precon.nl'),
  ('DTP03A', 21, 'purple', 'seed@precon.nl'),
  ('DTP03A', 22, 'purple', 'seed@precon.nl'),
  ('DTP03A', 23, 'purple', 'seed@precon.nl'),
  ('DTP03A', 24, 'purple', 'seed@precon.nl'),
  ('DTP03A', 25, 'purple', 'seed@precon.nl'),
  ('DTP03A', 26, 'purple', 'seed@precon.nl'),
  ('DTP03A', 27, 'purple', 'seed@precon.nl'),
  ('DTP03A', 28, 'purple', 'seed@precon.nl'),
  ('DTP03A', 29, 'purple', 'seed@precon.nl'),
  ('DTP03B', 10, 'green', 'seed@precon.nl'),
  ('DTP03B', 11, 'green', 'seed@precon.nl'),
  ('DTP03B', 12, 'green', 'seed@precon.nl'),
  ('DTP03B', 13, 'purple', 'seed@precon.nl'),
  ('DTP03B', 14, 'purple', 'seed@precon.nl'),
  ('DTP03B', 15, 'purple', 'seed@precon.nl'),
  ('DTP03B', 16, 'purple', 'seed@precon.nl'),
  ('DTP03B', 17, 'purple', 'seed@precon.nl'),
  ('DTP03B', 18, 'purple', 'seed@precon.nl'),
  ('DTP03B', 19, 'purple', 'seed@precon.nl'),
  ('DTP03B', 20, 'purple', 'seed@precon.nl'),
  ('DTP04', 7, 'red', 'seed@precon.nl'),
  ('DTP04', 8, 'red', 'seed@precon.nl'),
  ('DTP04', 9, 'green', 'seed@precon.nl'),
  ('DTP04', 10, 'amber', 'seed@precon.nl'),
  ('DTP04', 11, 'amber', 'seed@precon.nl'),
  ('DTP04', 12, 'amber', 'seed@precon.nl'),
  ('DTP04', 13, 'green', 'seed@precon.nl'),
  ('DTP04', 14, 'green', 'seed@precon.nl'),
  ('DTP04', 15, 'purple', 'seed@precon.nl'),
  ('DTP04', 16, 'purple', 'seed@precon.nl'),
  ('DTP04', 17, 'purple', 'seed@precon.nl'),
  ('DTP07', 5, 'green', 'seed@precon.nl'),
  ('DTP07', 6, 'green', 'seed@precon.nl'),
  ('DTP07', 7, 'amber', 'seed@precon.nl'),
  ('DTP07', 8, 'amber', 'seed@precon.nl'),
  ('DTP07', 9, 'red', 'seed@precon.nl'),
  ('DTP07', 10, 'red', 'seed@precon.nl'),
  ('DTP07', 11, 'red', 'seed@precon.nl'),
  ('DTP07', 12, 'amber', 'seed@precon.nl'),
  ('DTP07', 13, 'amber', 'seed@precon.nl'),
  ('DTP07', 14, 'purple', 'seed@precon.nl'),
  ('DTP08', 0, 'amber', 'seed@precon.nl'),
  ('DTP08', 1, 'amber', 'seed@precon.nl'),
  ('DTP08', 2, 'green', 'seed@precon.nl'),
  ('DTP08', 3, 'green', 'seed@precon.nl'),
  ('DTP08', 4, 'green', 'seed@precon.nl'),
  ('DTP08', 5, 'green', 'seed@precon.nl'),
  ('DTP08', 6, 'green', 'seed@precon.nl'),
  ('DTP08', 7, 'green', 'seed@precon.nl'),
  ('DTP08', 8, 'green', 'seed@precon.nl'),
  ('DTP08', 9, 'green', 'seed@precon.nl'),
  ('DTP08', 10, 'green', 'seed@precon.nl'),
  ('DTP08', 11, 'green', 'seed@precon.nl'),
  ('DTP08', 12, 'amber', 'seed@precon.nl'),
  ('DTP08', 13, 'amber', 'seed@precon.nl'),
  ('DTP09', 3, 'amber', 'seed@precon.nl'),
  ('DTP09', 4, 'amber', 'seed@precon.nl'),
  ('DTP09', 5, 'amber', 'seed@precon.nl'),
  ('DTP09', 6, 'amber', 'seed@precon.nl'),
  ('DTP09', 7, 'amber', 'seed@precon.nl'),
  ('DTP09', 8, 'amber', 'seed@precon.nl'),
  ('DTP09', 9, 'red', 'seed@precon.nl'),
  ('DTP09', 10, 'red', 'seed@precon.nl'),
  ('DTP09', 11, 'red', 'seed@precon.nl'),
  ('DTP09', 12, 'red', 'seed@precon.nl'),
  ('IMP01', 4, 'green', 'seed@precon.nl'),
  ('IMP01', 5, 'green', 'seed@precon.nl'),
  ('IMP01', 6, 'green', 'seed@precon.nl'),
  ('IMP01', 7, 'green', 'seed@precon.nl'),
  ('IMP01', 8, 'green', 'seed@precon.nl'),
  ('IMP01', 9, 'green', 'seed@precon.nl'),
  ('IMP01', 10, 'green', 'seed@precon.nl'),
  ('IMP01', 11, 'green', 'seed@precon.nl'),
  ('IMP01', 12, 'green', 'seed@precon.nl'),
  ('IMP01', 13, 'green', 'seed@precon.nl'),
  ('IMP02', 4, 'amber', 'seed@precon.nl'),
  ('IMP02', 5, 'green', 'seed@precon.nl'),
  ('IMP02', 6, 'green', 'seed@precon.nl'),
  ('IMP02', 7, 'green', 'seed@precon.nl'),
  ('IMP02', 8, 'red', 'seed@precon.nl'),
  ('IMP02', 9, 'red', 'seed@precon.nl'),
  ('IMP02', 10, 'red', 'seed@precon.nl'),
  ('IMP03', 6, 'amber', 'seed@precon.nl'),
  ('IMP03', 7, 'amber', 'seed@precon.nl'),
  ('IMP03', 8, 'amber', 'seed@precon.nl'),
  ('IMP03', 9, 'amber', 'seed@precon.nl'),
  ('IMP03', 10, 'amber', 'seed@precon.nl'),
  ('IMP03', 11, 'amber', 'seed@precon.nl'),
  ('IMP03', 12, 'amber', 'seed@precon.nl'),
  ('IMP03', 13, 'red', 'seed@precon.nl'),
  ('IMP03', 14, 'purple', 'seed@precon.nl'),
  ('IMP04', 4, 'green', 'seed@precon.nl'),
  ('IMP04', 5, 'green', 'seed@precon.nl'),
  ('IMP04', 6, 'green', 'seed@precon.nl'),
  ('IMP04', 7, 'green', 'seed@precon.nl'),
  ('IMP04', 8, 'green', 'seed@precon.nl'),
  ('IMP04', 9, 'green', 'seed@precon.nl'),
  ('IMP04', 10, 'amber', 'seed@precon.nl'),
  ('IMP04', 11, 'amber', 'seed@precon.nl'),
  ('IMP04', 12, 'amber', 'seed@precon.nl'),
  ('IMP04', 13, 'green', 'seed@precon.nl'),
  ('IMP04', 14, 'purple', 'seed@precon.nl'),
  ('IMP04', 15, 'purple', 'seed@precon.nl'),
  ('IMP04', 16, 'purple', 'seed@precon.nl'),
  ('IMP04', 17, 'purple', 'seed@precon.nl'),
  ('IMP04', 18, 'purple', 'seed@precon.nl'),
  ('IMP04', 19, 'purple', 'seed@precon.nl'),
  ('IMP04', 20, 'purple', 'seed@precon.nl'),
  ('IMP04', 21, 'purple', 'seed@precon.nl'),
  ('IMP04', 22, 'purple', 'seed@precon.nl'),
  ('IMP04', 23, 'purple', 'seed@precon.nl'),
  ('IMP04', 24, 'purple', 'seed@precon.nl'),
  ('IMP04', 25, 'purple', 'seed@precon.nl'),
  ('IMP04', 26, 'purple', 'seed@precon.nl');

INSERT INTO verbeterplanning_updates (project_code, text, created_by, created_at) VALUES
  ('KMO01', 'Resultaat: levert de nieuwe aanpak al meer sales op vanuit bestaande klanten?', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO01', '18-6: Aanpak is klaar, accountmanagers getraind en Nida en Silvion volgen dit periodiek op. 7 juli accountmanager dag is geannuleerd, dit nemen we verder op in de trainingslijn voor adviseurs 3.
Vraag: levert de nieuwe aanpak al meer sales op vanuit bestaande klanten?', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('KMO02', 'Vraag: heeft het groeiplan/ project gezorgd voor groei in België?', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO02', '01-06: Bram krijgt meer ruimte in ijn agenda en hoofd. Overdracht naar Sofie is niet echt geweest, gaa nu pas gebeuren. Zorgen dat het echt concreet wordt wie wat gaat doen en de uitvoering in. Moment kiezen om project te eindigen, volgende keer concreter zijn. Je zou op de groeilijn moeten zitten voordat je doorgaat en het in business as usual zet', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('KMO03', 'Vraag: heeft het groeiplan tot nu toe gezorgd voor extra omzet?', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO03', 'business en groeiplan nu parallel, als extra willen versnellen een beter commercieel plan maken. Komt een update door Brighid en Nora', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('KMO04', 'Voortgang: project heeft al gezorgd voor beter planningsproces en daarmee vollere planningen', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO04', 'Werkwijzen en processen zijn bijna klaar. 7 juli is afgelast dus we moeten op een ander moment gaan zorgen voor afstemming', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('KMO05', 'Nog geen resultaat tot nu toe. We geven het wel de kans tot einde van het jaar', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO07', 'Vraag resultaat: Hoe gaan we dit monitoren?', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('KMO07', 'Goed gestart!
Tot nu toe nog geen zichtbaar resultaat omdat net gestart.', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('KMO08', 'Marcel gaat in juli langs bij Fabrice. uiterlijk oktober hakken we een knoop door', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('KMO08', 'Al een aantal keer uitgesteld, we willen eerst groeiplan Frankrijk afronden', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('PK01', 'Besproken dat de trainingslijnen in scope blijven van dit project en daarmee dit project een jaar wordt verlengd', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('PK01', 'Vraag: vinden we dat we al beter voldaan aan de visie-essentie punt 3 & 4? En gaat eigenaarschap al omhoog? afgeleide indicatoren - wellicht te vroeg om iets van te zeggen?', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('PK01', 'Project loopt goed, framework staat, na een jaar bijna alle gesprekken gehad.', 'seed@precon.nl', '2026-06-18T11:59:58.000Z'),
  ('PK02', 'Vraag: draagt dit bij aan visie-essentie punt 3 en 4 en voldoen aan onze leiderschapsprincipes', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('PK02', 'Leiderschapsassessments lopen vollop. Opvolging door middel van coaching ook gestart. September analyse en terugkomdag', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('DTP01', 'Resultaat: nog weinig zichtbaar (alleen 2 offertes uit pilot). nog geen impact op recurrent sales gehad', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('DTP01', 'Pilot geëvalueerd op 5 mei. Marcel maakt nieuw plan. Volgende review erbij pakken', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('DTP02a', 'Positionering en vermarkting nog een groot thema. Nu een discussie gepland over de positionering. Marcel heeft contact met iemand die kan helpen met de vermarkting', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('DTP02a', 'Aan de slag met de eerste twee klanten. Zij kunnen meedenken / input en feedback geven over front-end en over de aansluiting op klant werkwijzen en andere klant systemen.
We hopen dan vanaf oktober elke maand een nieuwe klant aan te sluiten.', 'seed@precon.nl', '2026-06-30T11:59:59.000Z'),
  ('DTP02a', 'Resultaat: omzet verwachting nog onduidelijk', 'seed@precon.nl', '2026-06-18T11:59:58.000Z'),
  ('DTP02a', 'Gaat goed, tool bijna klaar om in gebruik te nemen.', 'seed@precon.nl', '2026-06-18T11:59:57.000Z'),
  ('DTP02b', 'Kapimex gaat starten als launching customer. Per 1 nov hopen we VINQ in te kunnen zetten en te valideren.  Nieuwe dossiers zullen via VINQ gaan. Oude dossiers nog even in PQP afhandelen. Per 1 dec hopen we intern uren te besparen door inzet VINQ. Inzet van VINQ voor nieuwe klanten vanaf 1 nov of 1 dec.', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('DTP02c', 'Belangrijk om hier Quasydoc ook in mee te nemen - wij leveren een stukje software om onze intelligentie in te bouwen.', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('DTP02c', 'We gaan vanaf nu testen met klanten (Biscuit International en Euroma)
We gaan vanaf 1 aug LIVE voor al onze klanten.
Op 7 juli houden we een webinar over de PPWR en onze VINQ tool. Intern moeten we zorgen dat een commercieel en een operationeel team klaarzit. Marketing goed betrekken. ', 'seed@precon.nl', '2026-06-30T11:59:59.000Z'),
  ('DTP02d', 'Deployment door Researchable, startend na aanleveren laatste Vibe-code (door Précon, Sander Verweij / Kim) op 1 sept a.s.
Sander zal GINO software nog verder bouwen.
Kim kijkt het na
Researchable zet alles goed en veilig.
LIVE en operationeel: 30 september (te bevestigen door Researchable).
Précon zal eerste klanten overzetten en test draaien: 1 okt – eind okt.
Précon gaat dan vanaf 1 nov huidige klanten (ca. 50 klanten) overzetten en mn ook nieuwe klanten aanhaken (1-2 per maand)', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('DTP03B', 'Jelle gaat een projectplanning maken', 'seed@precon.nl', '2026-06-30T12:00:00.000Z'),
  ('DTP03B', 'Op Précondag alle consultants getraind op AI geletterdheid', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('DTP04', 'Resultaat: doelstelling goed in het oog houden', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('DTP04', 'in besturingsoverleg besproken 19 mei, goede eerste oriëntatie. Nu verdiepingsslag voor 29 juli', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('DTP07', 'Resultaat: duurt langer dan verwacht maar gaat uiteindelijk wel lukken', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('DTP07', 'Ontwikkeling duurt lang. Klanten krijgen nu eerste test omgevingen te zien. Livegang lijkt einde van 2026 te worden', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('DTP08', 'Staan nu op een kruispunt - wel of niet doorgaan met de tool? Besluit komt op 9 juli.', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('DTP09', 'Resultaat nog niet behaald', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('DTP09', 'Besluit genomen om te stoppen met project en door te gaan in FLG 1.0 door nieuwe beheerder. FLG 3.0 wordt met AI gemaakt. Gino voorrang geven omdat het al op de plank ligt bij Researchable?', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('IMP01', 'Resultaat: kijken naar omzet', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('IMP01', 'Operationeel draaien van de business versus het project plan: zorgen dat we het goed documenteren zodat we er later op kunnen terugvallen.', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('IMP02', 'On Hold - resultaat tot nu toe niet gehaald door personele wisselingen', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('IMP03', 'Resultaat blijft uit', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('IMP03', 'Lastig voortgang te maken omdat geen concrete klantvragen', 'seed@precon.nl', '2026-06-18T11:59:59.000Z'),
  ('IMP04', 'Resultaat: certificering behaald!', 'seed@precon.nl', '2026-06-18T12:00:00.000Z'),
  ('IMP04', 'Bezig in kleine projecten om de certificering te behouden met nieuwe norm', 'seed@precon.nl', '2026-06-18T11:59:59.000Z');
